// Generated by scripts/generate-responsive-webp.js. Do not edit by hand.
export const RESPONSIVE_ASSETS = {
  "/assets/associations/associations_bg_texture": {
    "sourceWidth": 4896,
    "sourceHeight": 1977,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/associations/badge_row-1_01_high_vale_roof_tile": {
    "sourceWidth": 1179,
    "sourceHeight": 1150,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_02_century_seal_roof_assurance": {
    "sourceWidth": 1210,
    "sourceHeight": 1206,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_03_united_roofwrights": {
    "sourceWidth": 1123,
    "sourceHeight": 1196,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_04_aurelian_slate_council": {
    "sourceWidth": 985,
    "sourceHeight": 1187,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_05_royal_sheet_and_slate": {
    "sourceWidth": 943,
    "sourceHeight": 1303,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_06_crownwatch": {
    "sourceWidth": 1127,
    "sourceHeight": 1247,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_07_skyseer": {
    "sourceWidth": 1181,
    "sourceHeight": 1439,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_08_tempest": {
    "sourceWidth": 1133,
    "sourceHeight": 1249,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_09_emberward": {
    "sourceWidth": 1136,
    "sourceHeight": 1316,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_10_windmark": {
    "sourceWidth": 1113,
    "sourceHeight": 1316,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_11_hammerfall": {
    "sourceWidth": 1254,
    "sourceHeight": 1310,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_12_evergreen": {
    "sourceWidth": 1159,
    "sourceHeight": 1226,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_13_oldstone": {
    "sourceWidth": 1137,
    "sourceHeight": 1237,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_14_sunscale": {
    "sourceWidth": 1063,
    "sourceHeight": 1254,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_15_ironclad": {
    "sourceWidth": 1254,
    "sourceHeight": 1198,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_16_valeward": {
    "sourceWidth": 1079,
    "sourceHeight": 1185,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_17_verdant_peak": {
    "sourceWidth": 1168,
    "sourceHeight": 1195,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_18_everlight": {
    "sourceWidth": 1098,
    "sourceHeight": 1303,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_19_gildharbor": {
    "sourceWidth": 1306,
    "sourceHeight": 961,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_20_cinderpeak": {
    "sourceWidth": 1197,
    "sourceHeight": 1192,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_21_highspire": {
    "sourceWidth": 1133,
    "sourceHeight": 1172,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_22_highmere": {
    "sourceWidth": 1168,
    "sourceHeight": 1163,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-1_23_embercrest": {
    "sourceWidth": 1196,
    "sourceHeight": 1197,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_01_ironmere": {
    "sourceWidth": 1347,
    "sourceHeight": 880,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_02_stormglass": {
    "sourceWidth": 1523,
    "sourceHeight": 846,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_03_stonewake": {
    "sourceWidth": 2035,
    "sourceHeight": 660,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_04_ironpeak": {
    "sourceWidth": 1226,
    "sourceHeight": 1205,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_05_skyforge": {
    "sourceWidth": 1331,
    "sourceHeight": 1032,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_06_northreach": {
    "sourceWidth": 1751,
    "sourceHeight": 431,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_07_celestial_canopy_co-op": {
    "sourceWidth": 1194,
    "sourceHeight": 1199,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_08_wyverns_nest": {
    "sourceWidth": 1075,
    "sourceHeight": 1188,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_09_aegis": {
    "sourceWidth": 1429,
    "sourceHeight": 611,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_10_stoneweather": {
    "sourceWidth": 1153,
    "sourceHeight": 1098,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_11_skyreach": {
    "sourceWidth": 1448,
    "sourceHeight": 1032,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_12_thornwall": {
    "sourceWidth": 1277,
    "sourceHeight": 928,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_13_aurelian": {
    "sourceWidth": 1966,
    "sourceHeight": 629,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_14_eldercape": {
    "sourceWidth": 1046,
    "sourceHeight": 1194,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_15_gryphon": {
    "sourceWidth": 1284,
    "sourceHeight": 1021,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/associations/badge_row-2_16_moonkeep": {
    "sourceWidth": 1213,
    "sourceHeight": 1215,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/badges/badge-banner-workshirt-full-hem": {
    "sourceWidth": 1942,
    "sourceHeight": 150,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920
    ]
  },
  "/assets/badges/badge-banner-workshirt": {
    "sourceWidth": 1942,
    "sourceHeight": 156,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920
    ]
  },
  "/assets/badges/banner": {
    "sourceWidth": 2127,
    "sourceHeight": 171,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920
    ]
  },
  "/assets/customer service/customer_service_hologram_full": {
    "sourceWidth": 720,
    "sourceHeight": 1626,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/customer service/customer_service_hologram_puck": {
    "sourceWidth": 720,
    "sourceHeight": 1626,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/footer/brand-plaque": {
    "sourceWidth": 1905,
    "sourceHeight": 826,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/footer/footer-eaves-foreground": {
    "sourceWidth": 1672,
    "sourceHeight": 430,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/footer/footer-roofscape-backdrop": {
    "sourceWidth": 1672,
    "sourceHeight": 941,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/footer/map-frame": {
    "sourceWidth": 1672,
    "sourceHeight": 941,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/founder/founder-jean-texture": {
    "sourceWidth": 5472,
    "sourceHeight": 2644,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/founder/founder_left_frame": {
    "sourceWidth": 4274,
    "sourceHeight": 4887,
    "hasAlpha": true,
    "format": "avif",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/founder/founder_right_frame": {
    "sourceWidth": 6098,
    "sourceHeight": 4044,
    "hasAlpha": true,
    "format": "avif",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/gallery/01-gothic-mountain-house-copper-trim": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/02-curved-copper-coastal-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/03-white-metal-roof-gold-trim": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/04-butterfly-copper-roof-house": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/05-patina-copper-fantasy-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/06-tiered-dark-metal-roof-house": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/07-coastal-tile-and-patina-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/08-iridescent-curved-slate-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/09-desert-mixed-metal-tile-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/10-flared-copper-roof-house": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/11-mountain-lodge-slate-copper-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/12-weathered-patina-copper-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/13-turquoise-tile-copper-trim-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/14-lakeside-multicolor-slate-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/15-ornate-green-tile-copper-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/16-coastal-curved-shingle-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/17-desert-standing-seam-copper-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/18-curved-dark-shingle-lake-house": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/19-sunset-coastal-curved-roof-home": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/20-ornate-copper-slate-arched-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/21-purple-curved-metal-coastal-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/22-desert-copper-tile-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/23-purple-slate-copper-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/24-angular-white-metal-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/25-red-copper-slate-gothic-house": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/26-copper-turret-gothic-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/27-white-metal-gold-trim-coastal-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/28-cobalt-blue-tile-coastal-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/29-terracotta-tile-desert-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/30-sunset-lakeside-standing-seam-lodge": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/31-tiered-dark-standing-seam-roof": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/32-sunset-lakeside-copper-shingle-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/33-dark-slate-lakeside-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/34-iridescent-teal-tile-coastal-hotel": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/35-green-tile-copper-trim-lakeside-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/36-tan-tile-vineyard-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/37-silver-metal-tile-coastal-home": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/38-gold-hexagonal-tile-coastal-resort": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/39-cedar-shake-mountain-lodge": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/40-modern-solar-panel-roof-building": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/41-dark-slate-turret-coastal-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/42-tropical-thatch-oceanfront-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/43-modern-green-living-roof-building": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/44-curved-green-living-roof-building": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/45-cobalt-blue-tile-coastal-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/46-indigo-tile-coastal-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/47-red-terracotta-tile-coastal-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/48-terracotta-tile-mountain-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/49-grey-metal-standing-seam-lakeside-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/50-patina-metal-standing-seam-coastal-lodge": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/51-charcoal-standing-seam-lakeside-home": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/52-dark-metal-standing-seam-mountain-home": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/53-copper-shingle-turret-coastal-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/54-copper-shingle-oceanfront-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/55-charcoal-slate-lakeside-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/56-dark-slate-coastal-stone-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/57-patina-scalloped-tile-lakeside-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/58-iridescent-teal-diamond-tile-coastal-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/59-patina-scalloped-tile-coastal-chateau": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/60-green-scalloped-tile-copper-trim-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/61-sand-tile-coastal-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/62-cream-tile-waterfront-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/63-slate-grey-tile-coastal-home": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/64-light-grey-tile-coastal-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/65-gold-hexagonal-tile-waterfront-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/66-gold-scalloped-tile-tropical-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/67-cedar-shake-lakeside-lodge": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/68-cedar-shake-lakeside-estate": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/69-dark-solar-tile-lakeside-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/70-solar-tile-lakeside-stone-home": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/71-slate-blue-scalloped-tile-coastal-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/72-slate-blue-scalloped-tile-coastal-mansion": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/73-tropical-thatch-cliffside-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/74-thatch-roof-tropical-pool-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/75-living-green-roof-coastal-retreat": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/76-angular-green-living-roof-coastal-villa": {
    "sourceWidth": 1448,
    "sourceHeight": 1086,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/gallery/material-library": {
    "sourceWidth": 1013,
    "sourceHeight": 1520,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960
    ]
  },
  "/assets/gallery/paper_texture": {
    "sourceWidth": 2880,
    "sourceHeight": 1400,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/hero/foreground": {
    "sourceWidth": 2127,
    "sourceHeight": 734,
    "hasAlpha": true,
    "format": "avif",
    "widths": [
      640,
      960,
      1920
    ]
  },
  "/assets/hero/sky": {
    "sourceWidth": 4599,
    "sourceHeight": 734,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/navbar/navbar-underlayment": {
    "sourceWidth": 3627,
    "sourceHeight": 224,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/protection/copper_background_texture": {
    "sourceWidth": 3000,
    "sourceHeight": 1570,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/protection/powder-coated-navy-steel": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960
    ]
  },
  "/assets/protection/protection-finished-roof": {
    "sourceWidth": 1672,
    "sourceHeight": 941,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/protection/protection-underlayment": {
    "sourceWidth": 1672,
    "sourceHeight": 941,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/reviews/baeloon-pluhng": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/reviews/leaf_background_texture": {
    "sourceWidth": 3000,
    "sourceHeight": 1376,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/reviews/nyaren-klourm": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/reviews/roofing-felt-fiber": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960
    ]
  },
  "/assets/reviews/seris-rhuke": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/services/commercial-roofing": {
    "sourceWidth": 1287,
    "sourceHeight": 858,
    "hasAlpha": false,
    "format": "avif",
    "widths": [
      640,
      960
    ]
  },
  "/assets/services/custom-metal": {
    "sourceWidth": 1448,
    "sourceHeight": 965,
    "hasAlpha": false,
    "format": "avif",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/services/repairs-inspections": {
    "sourceWidth": 1536,
    "sourceHeight": 1024,
    "hasAlpha": false,
    "format": "avif",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/services/residential-roofing": {
    "sourceWidth": 1442,
    "sourceHeight": 962,
    "hasAlpha": false,
    "format": "avif",
    "widths": [
      640,
      960,
      1440
    ]
  },
  "/assets/services/services-cover-board": {
    "sourceWidth": 3000,
    "sourceHeight": 1094,
    "hasAlpha": false,
    "format": "avif",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/ui/copper-edge": {
    "sourceWidth": 7383,
    "sourceHeight": 82,
    "hasAlpha": false,
    "format": "webp",
    "widths": [
      640,
      960,
      1440,
      1920,
      2560
    ]
  },
  "/assets/ui/copper-sphere-etched-large-generated": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/ui/copper-sphere-etched-large-hover-left": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  },
  "/assets/ui/copper-sphere-etched-large-hover-right": {
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "hasAlpha": true,
    "format": "webp",
    "widths": [
      640
    ]
  }
} as const
